### ISSUE TITLE
websocket插件不能用了

### ISSUE THREAD

**Issue by zjt123** [openwebf/webf#10]
### What version of kraken are you using

改名字后 ，websocket插件不能用了

### Steps To Reproduce

**Code example:** 

**Expected results:** 

**Actual results:**

**Comment by andycall** [comment]
plugins are not ready yet.

**Comment by suyulin** [comment]
> ### What version of kraken are you using
> 改名字后 ，websocket插件不能用了
> 
> ### Steps To Reproduce
> **Code example:**
> 
> **Expected results:**
> 
> **Actual results:**
[websocket plugin ](https://github.com/openwebf/plugins/tree/main/packages/webf_websocket)is already work
