### ISSUE TITLE
method channel passes number error

### ISSUE THREAD

**Issue by liuzitong123a** [openwebf/webf#114]
### Affected version

main or 0.13.0-beta.9

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

1.  run example
2. pass the number using the method channel

### Code example

bundle.js
```
p.onclick = async function() {
  const id = await webf.methodChannel.invokeMethod("test");
  console.log(id);
}
```

main.dart
```
_javaScriptChannel.onMethodCall = (String method, arguments) async {
      if (method == 'test') {
        return await Future.value(111111111111111);
      }
};
```

### Expected results

output 111111111111111

### Actual results

output 307163591

**Comment by liuzitong123a** [comment]
<img width="915" alt="截屏2022-11-13 下午11 03 17" src="https://user-images.githubusercontent.com/27840778/201528541-45412a01-672a-4294-b380-b9faafc6c02a.png">

Should I use JS_NewInt64 here? @andycall

**Comment by andycall** [comment]
Is it works?

**Comment by liuzitong123a** [comment]
test is working properly

**Comment by andycall** [comment]
You can fire a PR to fix that.
