### ISSUE TITLE
如何判断北海里面的控件是否在屏？

### ISSUE THREAD

**Issue by zjt123** [openwebf/webf#180]
### Should this be an RFC?

- [X] This is not a substantial change

### Description

如何判断北海里面的控件是否在屏？

**Comment by devjiangzhou** [comment]
通过 JS 就可以实现吧，offsetTop - scrollTop <= viewPortHeight

**Comment by zjt123** [comment]
> 

只有offsetTop能有正常值，  document.scrollTop 获取不了，document.body.scrollTop 可以，viewPortHeight获取不了。

想问下dart的控件是怎么判断是否在屏的呢？

**Comment by devjiangzhou** [comment]
> > 通过 JS 就可以实现吧，offsetTop - document.scrollTop <= viewPortHeight
> 
> 只有offsetTop能有正常值， document.scrollTop 获取不了，document.body.scrollTop 可以，viewPortHeight获取不了。
> 
> @devjiangzhou 想问下dart的控件是怎么判断是否在屏的呢？

1. viewPortHeight:  document.body.clientHeight
2. 如果你说的 Dart 控件是指 WebF 混合渲染汇总的 Flutter Custom Element 的意思的话，都可以通过 JS 来判断

**Comment by andycall** [comment]
Element 上 appear 和 disappear 事件的实现
