### ISSUE TITLE
M1 IOS Simulator run error

### ISSUE THREAD

**Issue by suyulin** [openwebf/webf#20]
### What version of webf are you using

main/0.12

### Steps To Reproduce

run m1 ios simulator

**Code example:** 

**Expected results:** 
run surcess

**Actual results:** 
  BUILD FAILED , error is    ` ld: framework not found quickjs`
example  ios   run success

**Comment by Bisond** [comment]
What version of webf are you using

main/0.12.0+1

Steps To Reproduce
run intel ios simulator

Code example:

Expected results:
run surcess

Actual results:
BUILD FAILED , error is ld: framework not found quickjs
