### ISSUE TITLE
vue2 绑定点击事件小米4无效

### ISSUE THREAD

**Issue by wds24** [openwebf/webf#21]
### What version of webf are you using

最新分支

### Steps To Reproduce

运行vue2简单demo即可重现（vue3测试过没问题）

**Code example:** 

`<template>
  <div id="app">
    <div @click="handleClick" style="width: 300px; height: 300px">点我呀</div>
    {{ msg }}
  </div>
</template>

<script>
export default {
  name: 'App',
  components: {},
  data() {
    return { msg: '' }
  },
  methods: {
    handleClick() {
      console.log('clicked')
      this.msg = 'hello'
    }
  }
}
</script>`

**Expected results:** 
点击事件生效 & 有log输出

**Actual results:** 
无点击事件响应

**Comment by suyulin** [comment]
use this [demo](https://github.com/openkraken/samples/tree/main/demos)

**Comment by wds24** [comment]
> use this [demo](https://github.com/openkraken/samples/tree/main/demos)

demo都是vue3，我说的bug是指vue2

**Comment by XGHeaven** [comment]
请提供一个你本地可以复现的 demo，我试了官方创建的 vue2 demo，加上你这段代码是没问题的，能正确响应。

**Comment by wds24** [comment]
> 请提供一个你本地可以复现的 demo，我试了官方创建的 vue2 demo，加上你这段代码是没问题的，能正确响应。

只有在**小米4才会失效**，我在其他手机上也没发现问题

**Comment by XGHeaven** [comment]
小米 4 的机型有点老了，目前身边也没有测试机，可以尝试看看其他框架是否正常，以及无法响应的原因是 click 没触发还是触发但是响应式有问题了。可以尝试写个无框架的 DEMO 看看原因是什么。

**Comment by wds24** [comment]
> 小米 4 的机型有点老了，目前身边也没有测试机，可以尝试看看其他框架是否正常，以及无法响应的原因是 click 没触发还是触发但是响应式有问题了。可以尝试写个无框架的 DEMO 看看原因是什么。

我这边测试了下几台手机，手机**安卓系统是32位**的**VUE2**点击事件**都不行**，你可以用我说的系统试试

**Comment by wds24** [comment]
关闭，已新提
