### ISSUE TITLE
ios build 失败

### ISSUE THREAD

**Issue by 362228416** [openwebf/webf#236]
### Affected version

0.13.2+1

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

1、flutter create webf_test
2、cd webf_test
3、运行一个ios模拟器，我这里用的是ios15，iphone12（这里应该没有什么关系，因为我用xcode来编译也是失败）
4、flutter run

ios 启动失败，下面都是一些正常的编译信息，只有一些警告，没有error，没有更多的有效信息，macos 跟 android 可以启动成功，很苦恼，不知道什么原因

xcode 版本是xcode 13.1

### Code example

只是添加依赖就会导致变异失败，移除之后就可以编译，dart 还没有开始使用

### Expected results

ios 正常build

### Actual results

```bash
Launching lib/main.dart on iPhone 12 in debug mode...
Running pod install...                                           2,763ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         4.3s
Xcode build done.                                           24.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/ms/h9w4128x2cx3vrkkjmsmpkn00000gn/T/flutter_tools.hIiCwh/flutter_ios_build_temp_dirQk9XiK/temporary_xcresult_bundle

    warning: [CP] Unable to find matching .xcframework slice in 'ios-x86_64-simulator ios-arm64_armv7_armv7s' for the current build
    architectures (arm64 x86_64).
    warning: [CP] Unable to find matching .xcframework slice in 'ios-arm64_armv7_armv7s ios-x86_64-simulator' for the current build
    architectures (arm64 x86_64).

```

**Comment by devjiangzhou** [comment]
设备是 m1 么？

**Comment by 362228416** [comment]
@devjiangzhou  创建的是Iphone12模拟器，应该不是m1

**Comment by 362228416** [comment]
电脑型号：MacBook Pro (15-inch, 2017)
系统版本：11.5.2

**Comment by devjiangzhou** [comment]
https://github.com/openwebf/webf/blob/main/webf/example/ios/Podfile
替换成这个 Podfile 试试

**Comment by 362228416** [comment]
@devjiangzhou 
改了之后可以运行了，感谢！

**Comment by 362228416** [comment]
现在遇到一个新的问题，就是修改页面之后，js会实时编译，但是页面并不会刷新，需要返回上一个页面重新进入，这点比较麻烦，有什么好的办法能解决这个问题吗

**Comment by devjiangzhou** [comment]
HMR 是失效了么？ @andycall

**Comment by andycall** [comment]
Fixed on https://github.com/openwebf/webf/pulls?q=is%3Apr+is%3Aclosed
