### ISSUE TITLE
invoke_bindings_methods_from_native not initialized

### ISSUE THREAD

**Issue by liuzitong123a** [openwebf/webf#271]
### Affected version

main

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

run vue demo on macos 

### Code example

```
<script setup lang="ts">
import { ref, onMounted } from 'vue'

const myCanvas = ref()


onMounted(() => {
  setInterval(() => {
    console.log('setInterval')
    drawRect();
  }, 1000);
})

function drawRect() {
  const c = myCanvas.value;
  const ctx = c.getContext("2d");
  ctx.clearRect(0,0,200,200);
  ctx.fillStyle = '#A0A00F';
  ctx.fillRect(0, 0, 200, Math.ceil(Math.random() * 200));
}

</script>
<template>
  <canvas
    ref="myCanvas"
    :width="200"
    :height="200"
  />
</template>

```

### Expected results

![web](https://user-images.githubusercontent.com/27840778/222885896-a9eb26a4-206e-4419-9c19-c249e372170c.gif)

### Actual results

throw exception:
```
InternalError: Failed to call dart method: invoke_bindings_methods_from_native not initialized.
    at clearRect (native)
    at drawRect (internal://:19002:1)
    at <anonymous> (internal://:18996:1)
```

**Comment by andycall** [comment]
It appears that there are issues when calling getContext more than once on the same CanvasElement. The following code demonstrates this problem:

```
function drawRect() {
  const c = myCanvas.value;
  const ctx = c.getContext("2d"); <--- Only works at the first time.
  ctx.clearRect(0,0,200,200);
  ctx.fillStyle = '#A0A00F';
  ctx.fillRect(0, 0, 200, Math.ceil(Math.random() * 200));
}

```

Supporting multiple contexts in one CanvasElement can be complicated. To avoid this issue, it may be helpful to cache the ctx object so that you don't need to call getContext repeatedly in the drawRect function.
