### ISSUE TITLE
现在CSS解析模块支持::before，::after这些伪类元素么

### ISSUE THREAD

**Issue by yangtianrui95** [openwebf/webf#284]
### Feature type

CSS/DOM Style

### The spec link.

https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes

**Comment by andycall** [comment]
not support from now

**Comment by yangtianrui95** [comment]
可以指导一下么？ 我可以把这个功能做一下 @andycall

**Comment by andycall** [comment]
https://github.com/openwebf/webf/blob/main/webf/lib/src/css/parser/visitor.dart
