### ISSUE TITLE
使用gallery编译好的demo，测试发现canvas有掉帧的情况

### ISSUE THREAD

**Issue by snice** [openwebf/webf#288]
### Affected version

0.14.0-beta.4

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

1. clone [demo](https://github.com/snice/webf_demo)
2. 使用profile模式运行
3. 进入动画演示

### Code example

https://github.com/snice/webf_demo

### Expected results

稳定60帧

### Actual results

稳定了几秒钟后，掉到50帧

https://user-images.githubusercontent.com/8744870/225192924-59212019-6f30-4533-850d-61e67eb58c56.mp4

**Comment by andycall** [comment]
This demo is implemented using the DOM: 100 divs are moved using the 'transform: translateY()' property every frame

orignal version: https://animejs.com/

**Comment by snice** [comment]
> This demo is implemented using the DOM but no canvas: 100 divs are moved using the 'transform: translateY()' property every frame
> 
> orignal version: https://animejs.com/

Sorry, I made a mistake.

**Comment by andycall** [comment]
fixed in 0.14.0 due to the memory leaks in 0.13.2
