### ISSUE TITLE
overflow:scroll,if set maxWidth/maxHeight node size is error

### ISSUE THREAD

**Issue by pba-cra** [openwebf/webf#30]
### Affected version

0.12.0 and main

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

look code

### Code example

    let box = document.createElement('div');
    document.body.style.background= '#f92';
    document.body.style.width= '300px';
    document.body.style.height= '300px';
    document.body.style.display= 'flex';
    document.body.style.flexDirection= 'column';
    document.body.appendChild(box);

    box.style.background = '#6ad0e2';
    box.style.display = 'flex';
    box.style.flexDirection='column';

    const icon = document.createElement('div');
    icon.style.zIndex = 0;
    icon.style.background= '#f32';
    icon.style.maxHeight = '30px';
    icon.style.flexGrow = 1;
    icon.style.display = 'flex';
    icon.style.overflow = 'scroll';
    icon.style.fexShrink = 1

    box.appendChild(icon);

### Expected results

<img width="279" alt="截屏2022-08-19 18 17 57" src="https://user-images.githubusercontent.com/14161857/185598051-5ae1c3f5-ab4c-4969-bfef-60c7bb7d1650.png">

### Actual results

<img width="281" alt="截屏2022-08-19 18 19 08" src="https://user-images.githubusercontent.com/14161857/185598242-c45548a0-1b55-4d12-9bfa-13149dc7e8b6.png">

**Comment by XGHeaven** [comment]
So strange. I tried your demo code in chrome, the expected result looks different from you.

![image](https://user-images.githubusercontent.com/9291212/185645788-feb57b50-3b51-4aa2-bbd9-04bce685681f.png)

**Comment by XGHeaven** [comment]
Right, As you say, I must use the mobile device view in chrome.
But I don't know why it's different between desktop and mobile.
