### ISSUE TITLE
Cannot open some web pages

### ISSUE THREAD

**Issue by zhang-hu** [openwebf/webf#303]
### Affected version

0.13.3

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

On iPhone(iOS 15.6.1)
Flutter: 3.0.5

1. Open "https://www.baidu.com" with the WebF widget.

### Code example

``` Flutter
WebF(
    devToolsService: ChromeDevToolsService(),
    viewportWidth: viewportSize.width - queryData.padding.horizontal,
    viewportHeight: viewportSize.height - appBar.preferredSize.height - queryData.padding.vertical,
    bundle: WebFBundle.fromUrl('https://www.baidu.com'),
)
```

### Expected results

Home page of Baidu.

### Actual results

![2023_03_29_16_56_IMG_0018](https://user-images.githubusercontent.com/19181721/228482933-ab952677-1fb4-4c3f-b88c-9e4f032a18a2.PNG)

**Comment by zhang-hu** [comment]
Can WebF be used to implement a normal web browser?

**Comment by andycall** [comment]
No, even though WebF supports HTML/CSS and JavaScript, it should not be considered a web browser. Rendering untrusted code can be dangerous for users.
