### ISSUE TITLE
ReferenceError: 'localStorage' is not defined

### ISSUE THREAD

**Issue by Shu-Ji** [openwebf/webf#327]
### Feature type

DOM API

### The spec link.

https://developer.mozilla.org/zh-CN/docs/Web/API/Window/localStorage

### How much important for you

Will webf support the `localStorage` API?

**Comment by andycall** [comment]
You can use the `AsyncStorage` instead, it have the same API with `LocalStorage` but return a Promise than sync return.

**Comment by andycall** [comment]
https://openkraken.com/api/enhancement/storage

**Comment by Shu-Ji** [comment]
> https://openkraken.com/api/enhancement/storage

I have run some packages that need localStorage to exist. These libs need the standard localStorage APIs.

**Comment by andycall** [comment]
OK，we will add it in the future.
