### ISSUE TITLE
屏幕适配

### ISSUE THREAD

**Issue by zhangstar666** [openwebf/webf#33]
### Should this be an RFC?

- [x] This is not a substantial change

### Description

非常感谢这个库的存在！
目前正在使用webf，来运行H5，目前适配效果不是很好，很容易造成页面左右滑动，请问如何才能做好适配相关的工作呢？需要在Flutter 容器层做处理吗？

**Comment by zhangstar666** [comment]
> ` WebF(
            onControllerCreated: (controller) => controller,
            devToolsService:
                ChromeDevToolsService(), // Enable Chrome DevTools Services
            viewportWidth: viewportSize.width -
                queryData.padding.horizontal, // Adjust the viewportWidth
            viewportHeight: viewportSize.height -
                queryData.padding.vertical, // Adjust the viewportHeight
            bundle: WebFBundle.fromUrl(
                'https://www.star666.cn/low-code/home.js'), // The page entry point
          ),`
我想在JS里使用px进行布局。为了较好的适配移动端我需要做一个基于“基准像素”和APP侧的屏幕像素比转换。
目前webf里是支持rpx相对尺寸单位的，我还不清楚rpx这个相对单位是否还可以加上一个“基准像素”的比较。

**Comment by andycall** [comment]
rpx 是以整个屏幕来作为相对单位进行布局，最大值为 750。

如果想基于 viewportWidth 和 viewportHeight 来进行布局，可以使用 vw 和 vh。

px 是固定尺寸，但是不是物理像素，会自动依据屏幕缩放比来进行计算

**Comment by andycall** [comment]
推荐看下 CSS 标准中对单位适配的说明，这个问题实际上属于如何在 h5 中进行屏幕适配

https://developer.mozilla.org/en-US/docs/Web/CSS/length

**Comment by zhangstar666** [comment]
> 
vw、vh是可以的。也是一种百分比布局，
我的期望效果是：
Flutter容器层获取到px为单位的像素，再结合当前设备终端的缩放比把px固定尺寸，转换为逻辑像素。
类似：**realPx = H5Px * radio**
我想在Flutter容器层做这一层转换。

**Comment by andycall** [comment]
Flutter 中并不直接使用逻辑像素来进行布局，而是使用相对单位。如果你真的要逻辑像素的话，可以 * window.devicePixel

**Comment by zhangstar666** [comment]
> Flutter 中并不直接使用逻辑像素来进行布局，而是使用相对单位。如果你真的要逻辑像素的话，可以 * window.devicePixelRatio

是的。目前框架内部是没有做这个转换的吧。我准备自己在flutter绘制的时候，动态转换。

**Comment by andycall** [comment]
px 会直接转成 flutter 中的相对尺寸单位
