### ISSUE TITLE
input 标签的 checkbox 样式没有支持

### ISSUE THREAD

**Issue by bainian** [openwebf/webf#34]
### Affected version

main

### No same issues found

- [X] Yes, I search all issues but not found.

### Bug type

CSS/DOM Style

### Which frontend framework you are using.

H5

### Steps to reproduce

为input添加checkbox类型值即可复现。

### Code example

<p>
  <input type="checkbox" id="cbox1" value="first_checkbox">
  <label for="cbox1">This is the first checkbox</label>
</p>
<p>
  <input type="checkbox" id="cbox2" value="second_checkbox" checked="checked">
  <label for="cbox2">This is the second checkbox, which is checked</label>
</p>

### Expected results

显示checkbox样式。

### Actual results

显示的是默认输入框样式。

**Comment by xuzhongpeng** [comment]
https://github.com/openwebf/webf/commit/a271d23555f36565cc420b471f09db03a3cc52cf Using custom widget replace dom element and support checkbox

**Comment by xuzhongpeng** [comment]
related to #89
