### ISSUE TITLE
reload 或者 load 复杂的页面 几次 就会崩掉，而且内存不降

### ISSUE THREAD

**Issue by zjt123** [openwebf/webf#35]
### Affected version

main

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

F/libc    (15661): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 15830 (1.ui), pid 15661 (flutter_example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/cepheus/cepheus:10/QKQ1.190825.002/V12.0.6.0.QFACNXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-08-26 20:17:46+0800
pid: 15661, tid: 15830, name: 1.ui  >>> com.example <<<
uid: 10829
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
Cause: null pointer dereference
    x0  0000007894ebe200  x1  00000076e24b1af8  x2  ffffffffffffffff  x3  0000000000000005
    x4  00000000000001ac  x5  000000783c9de0b1  x6  000000000000000a  x7  000000000000000a
    x8  0000000000000000  x9  0000000000000000  x10 0000007815ad2374  x11 0000000000000000
    x12 66206120746f6e20  x13 0a6e6f6974636e75  x14 000000000000006f  x15 0000000000000000
    x16 0000007815b61380  x17 0000007815ad2340  x18 00000078337da000  x19 0000007894ebe200
    x20 0000007894ebe298  x21 000000783c663e00  x22 ffffffffffffffff  x23 00000076e24b1af0
    x24 000000783c99a6e0  x25 ffffffffffffffff  x26 0000007833aca020  x27 000000000000f890
    x28 0000000400000077  x29 0000007833ac9020
    sp  0000007833ac9020  lr  00000078158ab638  pc  0000007815ad238c
backtrace:
      #00 pc 000000000004c38c  /data/app/com.example-gZbO2tAf4PcMf5hqsFvJiQ==/lib/arm64/libquickjs.so (__JS_FreeValueRT+76) (BuildId: 35b47a52a8e61f4f004d5ce83902cc1972e703c4)
      #01 pc 0000000000095634  /data/app/com.example-gZbO2tAf4PcMf5hqsFvJiQ==/lib/arm64/libkraken.so (kraken::binding::qjs::handleInvokeModuleTransientCallback(void*, int, char const*, NativeString*)+768) (BuildId: 4698670a131d19019f67c2ca11703614453ceb83)
      #02 pc 0000000000006db4  [anon:dart-codespace]

### Code example

搞几个复杂的场景看看

### Expected results

..

### Actual results

..

**Comment by zhangstar666** [comment]
有没有具体的代码，或者发一个demo。

**Comment by andycall** [comment]
目前 bridge 正在重构，之前的旧代码已经不再维护，可以下个版本再看一下

**Comment by zjt123** [comment]
> 目前 bridge 正在重构，之前的旧代码已经不再维护，可以下个版本再看一下

下一版本预计什么时候、或者什么时候会提交到主分支？

**Comment by zjt123** [comment]
> 

你随便搞一下就可以了 。多reload或者load几次内存也不会降下去的

**Comment by zjt123** [comment]
> 有没有具体的代码，或者发一个demo。

你随便搞一下就可以了 。多reload或者load几次内存也不会降下去的

**Comment by andycall** [comment]
@zjt123 现在 main 分支还会有问题吗？

**Comment by zjt123** [comment]
> @zjt123 现在 main 分支还会有问题吗？

列表（图片文本）不停的请求加载更多数据内存一直增加

<img width="242" alt="9484d409b0acbb25872514489c4c8f2" src="https://user-images.githubusercontent.com/5286823/203483873-2cd5cdd0-0321-4013-917d-a27df9320cf5.png">
