### ISSUE TITLE
能不能把 three.js 移植过来，这样框架的知名度会提升不少的

### ISSUE THREAD

**Issue by pennyfine** [openwebf/webf#376]
### Should this be an RFC?

- [X] This is not a substantial change

### Description

商品或者模拟环境，教育领域需要大量的3D演示需求

**Comment by Eden-Harris** [comment]
这应该是webview实现才对，考虑到webf的知名度，还不如和uniapp合作，逐渐替代现有的weex引擎

**Comment by andycall** [comment]
3D 场景可以考虑用 unity 来实现，然后通过 flutter 嵌入到 webf 中去
