### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by charles0122** [openwebf/webf#385]
### Should this be an RFC?

- [X] This is not a substantial change

### Description

I'm very sorry to make this request.
The intl version used in this project conflicts with the version used in my project. I believe that the dependencies of this project should also be adjusted according to the updated version to adapt to the latest project.
Otherwise, I need to overload dependencies, and I don't know if there will be any security risks.
eg:
dependency_overrides:
  intl: ^0.18.0

**Comment by ndonkoHenri** [comment]
Facing this conflicts too. 
```
Because every version of flet from path depends on flutter_localizations from sdk
  which depends on intl 0.19.0, every version of flet from path requires intl 0.19.0.
And because webview_all >=0.4.3 depends on webf ^0.16.2 which depends on intl ^0.18.0,
  flet from path is incompatible with webview_all >=0.4.3.
So, because flet_webview depends on both webview_all ^0.4.5 and flet from path,
  version solving failed.
```

I tried to override the intl version, but it leads to issues. Will highly appreciate a solution or hint on how to solve this.

**Comment by christian4leaflabs** [comment]
I'm facing this issue too.

```
Because webf >=0.15.0 depends on intl ^0.18.0 and appflowy_editor >=2.5.0 depends on intl ^0.19.0, webf >=0.15.0 is incompatible with appflowy_editor >=2.5.0.
So, because delizyo_dashboard depends on both appflowy_editor ^3.3.0 and webf ^0.16.2, version solving failed.
```

A solution would be greatly appreciated.

**Comment by Ownistic** [comment]
I'm facing this issue too.

```
Because webf >=0.15.0 depends on intl ^0.18.0 and appflowy_editor >=2.5.0 depends on intl ^0.19.0, webf >=0.15.0 is incompatible with appflowy_editor >=2.5.0.
So, because delizyo_dashboard depends on both appflowy_editor ^3.3.0 and webf ^0.16.2, version solving failed.
```

A solution would be greatly appreciated.

**Comment by CleanCodix** [comment]
Same here.

webf intl dependency should be updated to allow us to use the latest Flutter version. 🙏

**Comment by cloud9business** [comment]
Also hitting the same issue.

Resolving dependencies...
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because webf >=0.15.0 depends on intl ^0.18.0 and every version of flutter_localizations from sdk depends on intl 0.19.0, webf >=0.15.0 is incompatible with flutter_localizations from sdk.
So, because client depends on both flutter_localizations from sdk and webf ^0.16.2, version solving failed.

**Comment by BluesYoung-web** [comment]
me too
