### ISSUE TITLE
iOS validate app失败：webf.framework/quickis.framework is not contained in acorrectly named directory

### ISSUE THREAD

**Issue by zhahouming** [openwebf/webf#386]
### Affected version

0.14.0

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

flutter版本
Flutter 3.7.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4b12645012 (10 weeks ago) • 2023-04-03 17:46:48 -0700
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1

截图：
![image](https://github.com/openwebf/webf/assets/16803650/7c9839ea-041e-4e87-a3f6-4671fe71db0e)

### Code example

flutter run没有问题，可以正常运行

### Expected results

xcode可以validate APP通过并上传至testflight

### Actual results

validate 失败

**Comment by l2js** [comment]
使用这个技术，IOS 版本可以正常过审吗？

**Comment by zhahouming** [comment]
> 使用这个技术，IOS 版本可以正常过审吗？

@l2js 暂时还没有测试过，按照以前了解到的信息，只要你不提应该可以过

**Comment by andycall** [comment]
需要发布前手动把  webf.framework 下面的多余 quickjs.framework webf_bridge.framework 删掉

**Comment by andycall** [comment]
WebF 使用 quickjs （Interpreter) 来执行 JavaScript 代码，没有任何动态下载可执行代码的功能，符合 Apple 开发者政策

```
3.3.2 Except as set forth in the next paragraph, an Application may not download or install
executable code. Interpreted code may be downloaded to an Application but only so long as
such code: (a) does not change the primary purpose of the Application by providing features or
functionality that are inconsistent with the intended and advertised purpose of the Application as
submitted to the App Store, (b) does not create a store or storefront for other code or
applications, and (c) does not bypass signing, sandbox, or other security features of the OS.
```

https://developer.apple.com/support/downloads/terms/apple-developer-program/Apple-Developer-Program-License-Agreement-20220606-English.pdf

**Comment by zhahouming** [comment]
> 需要发布前手动把 webf.framework 下面的多余 quickjs.framework webf_bridge.framework 删掉

@andycall 感谢支持！方案可行，已解决问题。建议其他遇到此问题的同学，在xcode每次运行Product > Archive之前删除这两个多余的framework，xcode中具体路径是Pods > Development Pods > webf > Frameworks，删除选项选择remove references，而不是直接删除原文件，这样可以避免下次运行时找不到相关文件

**Comment by zhoucong08141** [comment]
> > 需要发布前手动把 webf.framework 下面的多余 quickjs.framework webf_bridge.framework 删掉
> 
> @andycall 感谢支持！方案可行，已解决问题。建议其他遇到此问题的同学，在xcode每次运行Product > Archive之前删除这两个多余的framework，xcode中具体路径是Pods > Development Pods > webf > Frameworks，删除选项选择remove references，而不是直接删除原文件，这样可以避免下次运行时找不到相关文件

这个问题我是这么处理的 upload的时候会报错ERROR ITMS-90171
