### ISSUE TITLE
vue project v-if and sibling <br /> cause OOM and Null Pointer exception

### ISSUE THREAD

**Issue by weixing02** [openwebf/webf#437]
### Affected version

0.14.0

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

1. insert a`div` with two sibling `<br />` as child
2. insert two `div` seperately before & after the `div` created in step 1 and use` v-if` directive to control if renders.

better to check out the code example, pretty simple.

### Code example
```
<template>
	<div>
		<div v-if="show"></div>

		<div>
			222
			<br />
			<br />
		</div>

		<div v-if="show"></div>
	</div>
</template>

<script>
export default {
	data() {
		return {
			show: false
		}
	},

	mounted() {
		setTimeout(() => {
			this.show = true
		}, 2000)
	}
}
</script>

```

### Expected results

not stucked

### Actual results

report OOM & Null Pointer exception and stucked.

[log.txt](https://github.com/openwebf/webf/files/12167847/log.txt)

**Comment by XGHeaven** [comment]
You can try `main` branch code to check if it is fixed.

**Comment by weixing02** [comment]
> 

tried `main` branch code. still broken.

**Comment by XGHeaven** [comment]
I tested it in `main(0.15)`. It's works fine.

You can reopen it if you still not work. And better to provide a demo files for me.
