### ISSUE TITLE
内存占用严重，不释放

### ISSUE THREAD

**Issue by dpengfei** [openwebf/webf#482]
### Affected version

0.13.3

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

新建一个flutter app，在一级页面用webf加载一个js，高性能长列表是加载10000条数据，模拟器运行，内存占用1.5G，
跳转到下一页同样加载10000条数据的高性能长列表，内存直接暴涨到2.5G以上，点击导航栏返回一级页面，内存并未释放，使用真机测试，会因为内存占用过大被系统杀死app。

### Code example

JS：

const container = document.createElement('div');
// 修改 display 为 sliver.
container.style.display = 'sliver';
// 必须指定渲染容器节点滚动方向的尺寸(height).
container.style.height = '60vh';

// 创建 10000 个子节点.
for (let i = 0; i < 10000; i++) {
  const ele = document.createElement('div');
  ele.style.background = i % 2 ? '#fff' : '#e6e6e6';
  // Sliver 元素默认滚动方向为垂直方向
  // 它的子元素在水平方向上的尺寸(width)会被自动撑满.
  ele.style.padding = '35rpx 60rpx';
  ele.appendChild(document.createTextNode(`第 ${i + 1} 个元素`));
  }
  container.appendChild(ele);
}
document.body.appendChild(container);

dart：

Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: [
          _buildHeader(),
            WebF(
              bundle: WebFBundle.fromUrl('file://$urlPath'),
            ),
        ],
      ),
    );
  }

  Widget _buildHeader() {
    return GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTap: () {
        Navigator.pushNamed(context, '/next', arguments: {'id': 1});
      },
      child: const Text('点击跳转'),
    );
  }

### Expected results

加载内存占用影响较小，从二级页面返回一级页面，二级页面占用的内存释放

### Actual results

![BD89A4BE-E48C-45E7-A3C2-01F745EC54FF](https://github.com/openwebf/webf/assets/7112284/93dc8ccd-5915-45d9-96d3-3ba52e5a6608)

**Comment by zongren** [comment]
屏幕外的数据也会绘制？

**Comment by andycall** [comment]
老版本存在这个问题，需要再试一下 0.15.0 版本

**Comment by dpengfei** [comment]
flutter更新到3.10.6版本，使用webf 0.15.0，在mac上用模拟器验证，工程是flutter create命令创建的新工程，还是一样的内存不释放

**Comment by dpengfei** [comment]
> 老版本存在这个问题，需要再试一下 0.15.0 版本

flutter更新到3.10.6版本，使用webf 0.15.0，在mac上用模拟器验证，工程是flutter create命令创建的新工程，还是一样的内存不释放

**Comment by andycall** [comment]
@dpengfei Fixed at https://github.com/openwebf/webf/pull/487
