### ISSUE TITLE
[BUG] `LocalStorageModule` automatically inits `homePath` for `Hive`

### ISSUE THREAD

**Issue by AlexV525** [openwebf/webf#489]
### Affected version

[0.14.0, 0.15.0] https://github.com/openwebf/webf/commit/469012f37c5416c93320a04f605f079bf5167817

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

1. Create an example that is using Hive and WebF.
2. Call `Hive.init(anotherPath)` at the beginning of the app.
3. Open a box named `foo_box_name` and write something.
4. Construct a WebF widget (let `LocalStorageModule` initialize).
5. Open the `foo_box_name` box again, it actually opens another box under the module's path.

### Expected results

The module should not override the home path or can be configured to not initialize the home path.

### Actual results

The home path was overridden by the module.

### Workaround

https://github.com/AstroxNetwork/flutter_webf/commit/eb95a178cad5395a32f6f899c67943e2716e9867

**Comment by andycall** [comment]
Fixed at https://github.com/openwebf/webf/pull/504
