### ISSUE TITLE
No Directionality widget found. | RichText widgets require a Directionality

### ISSUE THREAD

**Issue by J-Yaleen** [openwebf/webf#496]
### Affected version

0.15.0+2

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

和这个步骤一样
https://pub.dev/packages/webf

### Code example

import 'package:flutter/material.dart';

import 'package:webf/webf.dart';
import 'package:webf/devtools.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    final MediaQueryData queryData = MediaQuery.of(context);
    final Size viewportSize = queryData.size;

    return Scaffold(
        body: Center(
      child: Column(
        children: [
          WebF(
            devToolsService:
                ChromeDevToolsService(), // Enable Chrome DevTools Services
            viewportWidth: viewportSize.width -
                queryData.padding.horizontal, // Adjust the viewportWidth
            viewportHeight: viewportSize.height -
                queryData.padding.vertical, // Adjust the viewportHeight
            bundle: WebFBundle.fromUrl(
                'http://localhost:5173/'), // The page entry point
          ),
        ],
      ),
    ));
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

### Expected results

正常跑起来

### Actual results

The following assertion was thrown building Scaffold(dirty, state: ScaffoldState#751ae(tickers:
           tracking 2 tickers)):
           No Directionality widget found.
           Scaffold widgets require a Directionality widget ancestor.
           The specific widget that could not find a Directionality ancestor was:
             Scaffold
           The ownership chain for the affected widget is: "Scaffold ← MyApp ← MediaQuery ← _MediaQueryFromView
             ← _ViewScope ← View-[GlobalObjectKey FlutterView#01241] ← [root]"
           Typically, the Directionality widget is introduced by the MaterialApp or WidgetsApp widget at the
           top of your application widget tree. It determines the ambient reading direction and is used, for
           example, to determine how to lay out text, how to interpret "start" and "end" values, and to resolve
           EdgeInsetsDirectional, AlignmentDirectional, and other *Directional objects.
           
           The relevant error-causing widget was:
             Scaffold Scaffold:file:///Users/kuban/Desktop/kuban-project/flutter/duomi_app/lib/main.dart:19:12

**Comment by andycall** [comment]
It seems like the problems is in your codes in `main.dart` not webf itself.

```
The following assertion was thrown building Scaffold(dirty, state: ScaffoldState#751ae(tickers:
tracking 2 tickers)):
No Directionality widget found.
```
