### ISSUE TITLE
Failed to load dynamic library '$ORIGIN/libwebf.so'

### ISSUE THREAD

**Issue by xiaocode** [openwebf/webf#51]
### Affected version

0.12.0

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

1.Clone the project
2.Enter the example folder
3.Run command "flutter run"

### Code example

no code

### Expected results

no expected results

### Actual results

Unhandled Exception: Invalid argument(s): Failed to load dynamic library '$ORIGIN/libwebf.so': $ORIGIN/libwebf.so: cannot open shared object file: No such file or directory

**Comment by XGHeaven** [comment]
You need to build bridge code with `npm run build:bridge:macos` command before flutter run.

**Comment by xiaocode** [comment]
> You need to build bridge code with `npm run build:bridge:macos` command before flutter run.

After I ran this command,I got another error:
"[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel webf)"
