### ISSUE TITLE
iOS upload to appstore faild: ERROR ITMS-90171

### ISSUE THREAD

**Issue by zhoucong08141** [openwebf/webf#593]
### Affected version

0.14.3

### Flutter versions

3.7.12

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

ERROR ITMS-90171 : "Invalid Bundle Structure - The binary file '' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

### Code example

ERROR ITMS-90171 : "Invalid Bundle Structure - The binary file '' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

### Expected results

<img width="724" alt="企业微信截图_ce247cc4-6b4b-4287-942d-3b6d374749ec" src="https://github.com/openwebf/webf/assets/74086261/a9bd4761-7468-40db-bac0-65389732deec">

### Actual results

<img width="724" alt="企业微信截图_ce247cc4-6b4b-4287-942d-3b6d374749ec" src="https://github.com/openwebf/webf/assets/74086261/70d38b97-9561-4e91-8e91-c58e456b7540">

**Comment by andycall** [comment]
Remove the `quickjs.framework/quickjs` and `webf_bridge.framework/webf_bridge` manually.

https://github.com/openwebf/webf/issues/386

**Comment by zhoucong08141** [comment]
delete this page
![Uploading 企业微信截图_9e03c0f7-4c48-4a84-95ad-4e5291d5ec5b.png…]()
