### ISSUE TITLE
Asset validation failed

### ISSUE THREAD

**Issue by wang-haiou** [openwebf/webf#594]
### Affected version

0.14.3

### Flutter versions

3.7.12

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

iOS 上传到App Store时报错如下:
Invalid bundle structure. The “HaoHuanProject.app/webf_bridge.xcframework/ios-arm64/webf_bridge.framework/webf_bridge” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundl

### Code example

1

### Expected results

1

### Actual results

<img width="745" alt="iShot_2024-04-07_19 45 02" src="https://github.com/openwebf/webf/assets/16330139/edb9d713-26f0-401c-9e86-8ee31b988949">

**Comment by andycall** [comment]
https://github.com/openwebf/webf/issues/386

参考这个需要发布前手动把 webf.framework 下面的多余 quickjs.framework webf_bridge.framework 删掉

**Comment by wang-haiou** [comment]
> #386
> 
> 参考这个需要发布前手动把 webf.framework 下面的多余 quickjs.framework webf_bridge.framework 删掉

按里面方法多次尝试，依然不行，还是上面的报错；

**Comment by HonchWong** [comment]
> > #386
> > 参考这个需要发布前手动把 webf.framework 下面的多余 quickjs.framework webf_bridge.framework 删掉
> 
> 按里面方法多次尝试，依然不行，还是上面的报错；

你工程里是怎么样集成Flutter的呀，是add_to_app的形式么 https://github.com/flutter/samples/tree/main/add_to_app 。看报错是链接的xcframework里包含可执行文件，这是第一次集成webf？还是之前集成是没问题的，最近才出问题

**Comment by wang-haiou** [comment]
> > > #386
> > > 参考这个需要发布前手动把webf.framework放在下面的多余quickjs.framework webf_bridge.framework删掉
> > 
> > 
> > 所有内容方法多次尝试，仍然不行，还是上面的报错；
> 
> 你工程里是怎么样集成Flutter的呀，是add_to_app的形式么https://github.com/flutter/samples/tree/main/add_to_app。看报错是链接的xcframework里包含了可执行文件，这是第一个次集成webf？还是之前集成是没问题的，最近才出问题

flutter 是pod添加的；是第一个次集成webf，之前没执行过，首次就有问题了，而且Flutter版本暂时还不能升级；

**Comment by wang-haiou** [comment]
解决了。将xxx.xcarchive包中的Project.app包里的quickjs.xcframework、webf_bridge.xcframework文件夹删掉，再上传就可以了，意味着每次打包后都需要手动删除一下这两个文件。

**Comment by andycall** [comment]
@wang-haiou https://github.com/openwebf/webf/pull/600 找到问题了，后面不用再这样搞了
