### ISSUE TITLE
preLoad和preRendering模式下不支持dart&js通信吗？

### ISSUE THREAD

**Issue by younglbj** [openwebf/webf#619]
### Affected version

0.16.0

### Flutter versions

3.13.8

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

     预加载模式下js与dart进行通信

### Code example

预加载模式下js与dart进行通信

### Expected results

    预加载模式下js与dart进行通信

### Actual results

预加载模式下js与dart进行通信

**Comment by andycall** [comment]
理论上是支持的，可能是bug。能提供具体的案例吗

**Comment by younglbj** [comment]
已解决

**Comment by fghjhuang** [comment]
问一下怎么解决，我也遇到这个问题

**Comment by fghjhuang** [comment]
我也解决了，不用回答啦
