### ISSUE TITLE
本地开发的时候会报错SocketException (SocketException: Connection failed (OS Error: No route to host, errno = 65), address = xxxx, port = 8080)

### ISSUE THREAD

**Issue by younglbj** [openwebf/webf#620]
### Affected version

0.16.0

### Flutter versions

3.13.8

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

SocketException (SocketException: Connection failed (OS Error: No route to host, errno = 65), address = 10.161.118.142, port = 8080)

### Code example

`child: WebF(
            bundle: WebFBundle.fromUrl(
                'http://10.161.118.142:8080/xxx'),
            javaScriptChannel: javaScriptChannel,
          ),`

### Expected results

正常页面展示

### Actual results

![111](https://github.com/openwebf/webf/assets/29365700/56fa9d0b-fd61-4a8f-9ad9-a638697fe975)

**Comment by andycall** [comment]
检查网络问题
