### ISSUE TITLE
还在维护吗，能不能入坑

### ISSUE THREAD

**Issue by Tlanglord** [openwebf/webf#627]

**Comment by andycall** [comment]
??? 没看到现在的工作吗

**Comment by andycall** [comment]
https://www.zhihu.com/question/660518113/answer/3550696124

我都拿到奇绩投资全职创业了，你说呢？

**Comment by kingson09** [comment]
> https://www.zhihu.com/question/660518113/answer/3550696124
> 
> 刚拿到奇绩投资全职创业了，你说呢？

有什么大型项目应用的案例吗

**Comment by andycall** [comment]
<img width="387" alt="image" src="https://github.com/user-attachments/assets/05054a1f-f2ec-44f2-ab3b-2f84e03b52f7">
