### ISSUE TITLE
android addJavascriptInterface兼容

### ISSUE THREAD

**Issue by Tlanglord** [openwebf/webf#631]
### Affected version

v0.16.0

### No same issues found

- [X] Yes, I search all issues but not found.

### Bug type

JavaScript

### Steps to reproduce

android中h5通信，android侧调用addJavascriptInterface(xxx, androidObj)注册 ，js侧调用 window.androidObj.func()方式和native通信，在现有的方案上是否能提供更好的方式，不用修改原有的逻辑

### Expected results

不修改h5 js侧原有逻辑，还是基于window.androidObj.func()

### Actual results

无

**Comment by andycall** [comment]
目前只有 Dart < --> JS 的通信方案，你可以按照下面的思路来：

1. 用 Flutter 的 methodChannel 实现 Java 与 Dart 的通信
2. 按照下面的教程实现 Dart 与 JS 的教程
https://openwebf.com/docs/tutorials/guides-for-flutter-developer/dart_js_intercommunication
3. 将 webf.methodChannel 的 API 再用 JS 封装一下，包装成 window.androidObj.func()
