### ISSUE TITLE
example 运行不正确,点击 open webf page 会白屏

### ISSUE THREAD

**Issue by September999999999** [openwebf/webf#632]
### Affected version

0.16.1

### Flutter versions

3.22.3

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

运行https://github.com/openwebf/webf/blob/main/webf/example/lib/main.dart 的代码

### Code example

/*
 * Copyright (C) 2019-2022 The Kraken authors. All rights reserved.
 * Copyright (C) 2022-present The WebF authors. All rights reserved.
 */

import 'package:flutter/material.dart';
import 'package:webf/webf.dart';
import 'package:webf/devtools.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Kraken Browser',
      // theme: ThemeData.dark(),
      debugShowCheckedModeBanner: false,
      home: FirstPage(title: 'Landing Bay'),
    );
  }
}

class FirstPage extends StatefulWidget {
  const FirstPage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<StatefulWidget> createState() {
    return FirstPageState();
  }
}

class FirstPageState extends State<FirstPage> {
  late WebFController controller;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    controller = WebFController(
      context,
      devToolsService: ChromeDevToolsService(),
    );
    controller.preload(WebFBundle.fromUrl('assets:assets/bundle.html'));
  }

  @override
  void dispose() {
    super.dispose();
    controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.push(context, MaterialPageRoute(builder: (context) {
              return WebFDemo(controller: controller);
            }));
          },
          child: const Text('Open WebF Page'),
        ),
      ),
    );
  }
}

class WebFDemo extends StatelessWidget {
  final WebFController controller;

  WebFDemo({ required this.controller });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('WebF Demo'),
        ),
        body: Center(
          // Center is a layout widget. It takes a single child and positions it
          // in the middle of the parent.
          child: WebF(controller: controller),
        ));
  }
}

### Expected results

我想知道webf example正常运行的效果

### Actual results

![img_v3_02ct_15b21d92-b14b-4d9e-b497-ded7001a413g](https://github.com/user-attachments/assets/dbd9f5e4-602b-4e76-9e81-336af728ef17)

**Comment by Tlanglord** [comment]
![WX20240718-181246@2x](https://github.com/user-attachments/assets/fa38c66a-ec1a-47c7-a24d-455fa705c7c1)
@September999999999

**Comment by andycall** [comment]
源码模式执行需要看下这个 https://github.com/openwebf/webf/blob/main/.github/CONTRIBUTING.md
