### ISSUE TITLE
跑网页显示兼容性问题

### ISSUE THREAD

**Issue by dongqiangqiang-tal** [openwebf/webf#634]
### Affected version

v0.16.0

### No same issues found

- [X] Yes, I search all issues but not found.

### Bug type

CSS/DOM Style

### Steps to reproduce

跑了下主流的一些网页集中反馈下bug：
1. tencent.com , 显示异常
2. sina.com.cn , 提示：打开javascript支持
3. 163.com ，白屏 ，提示：onJSError: SyntaxError: unexpected token in expression: '<'
4. baidu.com , crash ,  提示： Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x28 in tid 20140 (JS Worker 1), pid 19916 (bf.webf_example)

### Expected results

修改下兼容性问题

### Actual results

tencent.com  ![tencent](https://github.com/user-attachments/assets/a65e8a7d-7a30-49d0-b307-70df58f4a4aa)

**Comment by andycall** [comment]
WebF 不是浏览器，请不要拿来访问任意网页使用
