### ISSUE TITLE
After the jump of tag a, the channels of dart and js are no longer useful

### ISSUE THREAD

**Issue by chengming111** [openwebf/webf#652]
### Affected version

0.16.2

### Flutter versions

3.22.3

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

After clicking the Submit button on the homepage, the loading animation can be displayed normally, but after the page jumps, an error message appears when clicking the Submit button.

### Code example

1. There is a function 'submitMap' in plugin
    submitMap(jsonString) {
        return webf.methodChannel.invokeMethod('submitMap', jsonString);
    }

2. in dart
    case 'submitMap':
        showLoading();
        // Simulate processing, hide the loading after 2 seconds
        await Future.delayed(Duration(seconds: 2));
        hiddenLoading();
        onSubmit(args[0]);
        return null;

3.  In html and js, I have
     <button type="submit" id="submit" class="submit">提交</button>
     
     const submit = document.getElementById('submit');
     submit.addEventListener('click', async(e) => {
         ......
         await window.form.submitMap(jsonString);
     });

### Expected results

loading animation

### Actual results

![截屏2024-08-22 16 16 09](https://github.com/user-attachments/assets/f9f6fb0c-515c-40d3-a074-565a22caf1e4)

**Comment by andycall** [comment]
let me check it out

**Comment by chengming111** [comment]
非常感谢您的回复。请问您查看了吗，可以正常使用吗

**Comment by andycall** [comment]
近期都在处理商业技术支持（24小时内响应），社区支持只能在空闲时间搞一下，平均响应时间在 1-2 周。

最近客户需求有点多，还请耐心等待

**Comment by andycall** [comment]
@chengming111  
```
window.form
```
这个是在哪里定义的，你在哪里注入了一个脚本来实现了这个函数？

**Comment by chengming111** [comment]
您好，我在assets/plugin/base_plugin.js 中定义的

```
class Form {
    constructor() {};

    // 用户点击提交按钮后，将数据传回dart
    submitMap(jsonString) {
        return webf.methodChannel.invokeMethod('submitMap', jsonString);
    }

  
}
window.form = new Form();
```

**Comment by andycall** [comment]
通过 script 标签引入的吗

**Comment by chengming111** [comment]
是的

**Comment by andycall** [comment]
@chengming111 我尝试按你的步骤写了个 demo，但是依然没有复现，具体有关跳转的操作没有提供相应的代码。

https://github.com/andycall/webf-issue-demo-652

需要提供可复现的 demo
