### ISSUE TITLE
可以获得JavaScript运行时对象的地址，在dart中进行访问

### ISSUE THREAD

**Issue by Lloyd-Montgomery-Garmadon** [openwebf/webf#692]
我想拿到JavaScript运行时变量的地址，进行读取，有没有方法可以实现，或者类似的功能

**Comment by andycall** [comment]
这个是要做啥？ bindingObject 还不够用吗

**Comment by Lloyd-Montgomery-Garmadon** [comment]
我是个初学者，我看到了bindingObject，但是不明白怎么使用

**Comment by Lloyd-Montgomery-Garmadon** [comment]
> 这个是要做啥？ bindingObject 还不够用吗

可以继承bindingObject，把js中的变量，绑定到Flutter中吗，或者是把继承自bindingObject的类，在js中new出来

**Comment by andycall** [comment]
https://openwebf.com/docs/tutorials/guides-for-flutter-developer/flutter_widget_element
https://openwebf.com/docs/tutorials/guides-for-flutter-developer/dart_js_intercommunication

你是不是在寻找这个

**Comment by Lloyd-Montgomery-Garmadon** [comment]
> https://openwebf.com/docs/tutorials/guides-for-flutter-developer/flutter_widget_element https://openwebf.com/docs/tutorials/guides-for-flutter-developer/dart_js_intercommunication
> 
> 你是不是在寻找这个
差不多，可以解决我的问题，谢谢
