### ISSUE TITLE
会兼容支持 HarmonyNext 的非官方 Flutter 吗？ Will it be compatible with HarmonyNext?

### ISSUE THREAD

**Issue by looplake** [openwebf/webf#694]
### Should this be an RFC?

- [X] This is not a substantial change

### Description

感谢贡献者的付出, 我没有能力去改变它, 想问下是否有计划兼容非官方harmony版本的flutter?

Thanks to the contributors, I don't have the ability to change it, and wanted to ask if there are any plans to make it compatible with unofficial harmony versions of flutter?

[OpenHarmony-SIG](https://gitee.com/openharmony-sig)/[flutter_flutter](https://gitee.com/openharmony-sig/flutter_flutter)： https://gitee.com/openharmony-sig/flutter_flutter

**Comment by andycall** [comment]
暂时没有，这个项目的主要方向是出海。我们没有多余的精力来关注国内开发者的需求了
