### ISSUE TITLE
dart端调用js方法，怎么携带参数。

### ISSUE THREAD

**Issue by Lloyd-Montgomery-Garmadon** [openwebf/webf#696]
作者你好，根据在这里面的步骤，https://openwebf.com/docs/tutorials/guides-for-flutter-developer/dart_js_intercommunication，我执行不了带参数的调用，可以解答一下吗

**Comment by andycall** [comment]
```  
let result = await webf.methodChannel.invokeMethod('helloworld', 'abc');
```

直接放到 invokeMethod 就行，这些值都会传递到 dart 那侧的 List<dynamic> args 数组内

**Comment by Lloyd-Montgomery-Garmadon** [comment]
> ```
> let result = await webf.methodChannel.invokeMethod('helloworld', 'abc');
> ```
> 
> 直接放到 invokeMethod 就行，这些值都会传递到 dart 那侧的 List args 数组内

function reasonOnChange(i) {
    console.log('Change 事件触发成功:');
    console.log('事件附带的数据:', i);
}
我想在dart中调用js的这个方法，同时传递参数，可以说一下怎么在dart中调用吗
