### ISSUE TITLE
Linux issue on official demo!

### ISSUE THREAD

**Issue by fisherjoe** [openwebf/webf#703]
### Affected version

0.16.2

### Flutter versions

3.24.4

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

On path "webf-main/webf/example" run "flutter build linux"

Platform info:
Static hostname: dw223
Icon name: computer
Machine ID: dbfef1aa0b064bcf9d30ec3ad0886edb
Boot ID: 42133b83ded844709ef5eb12beb988ee
Operating System: Ubuntu 20.04.6 LTS
Kernel: Linux 5.10.120-tegra
Architecture: arm64

### Code example

As officiel demo.

### Expected results

Build success !

### Actual results

CMake Error at flutter/ephemeral/.plugin_symlinks/webf/linux/CMakeLists.txt:35 (add_subdirectory):
  add_subdirectory given source
  "/home/yingzi/webf-main/webf/example/linux/flutter/ephemeral/.plugin_symlinks/webf/linux/../src"
  which is not an existing directory.

**Comment by andycall** [comment]
See the guide on https://github.com/openwebf/webf/blob/main/.github/CONTRIBUTING.md, and don't forget to clone the source with submodule commands:

```
git clone git@github.com:openwebf/webf.git
git submodule update --init --recursive
```
